"""
Multi-language UI translation dictionaries.
Only UI labels are translated — NLP preprocessing remains Indonesian-focused.
"""

LANGUAGES = {
    "en": {
        "lang_name": "English",
        # Sidebar
        "sidebar_title": "PUBG Mobile",
        "sidebar_subtitle": "Sentiment Analysis",
        "data_source": "Data Source",
        "data_source_sample": "Default Data (Sample)",
        "data_source_scrape": "Scrape Real Data",
        "data_source_upload": "Upload CSV",
        "upload_csv": "Upload CSV file",
        "load_sample": "🔄 Load Sample Data",
        "load_sample_spinner": "Generating sample data...",
        "load_sample_success": "reviews loaded",
        "rows_loaded": "rows loaded",
        "scrape_btn": "🔍 Scrape & Load Data",
        "scrape_spinner": "Scraping {count} reviews from App Store ({countries})...",
        "scrape_success": "reviews successfully scraped!",
        "scrape_fail": "❌ Failed to fetch data. Please check your internet connection.",
        "select_countries": "Select Countries",
        "select_all": "Select All Countries",
        "review_count": "Total Reviews",
        "filter_version": "🔖 Filter App Version",
        "model_config": "⚙️ Model Configuration",
        "ngram_type": "N-Gram Type",
        "use_stemming": "Use Stemming",
        "test_size": "Test Set Size (%)",
        "train_btn": "🚀 Train Model",
        "compare_btn": "📊 Compare N-Grams",
        "language_label": "🌐 Language",
        "copyright": "© 2025 — Naïve Bayes N-Gram Sentiment Analysis",
        # Hero banner
        "hero_title": "🎮 PUBG Mobile Sentiment Analysis",
        "hero_desc": "Interactive dashboard for analyzing App Store review sentiments using Naïve Bayes Classifier & N-Gram",
        # Tabs
        "tab_explore": "📊 Data Exploration",
        "tab_preprocess": "🔧 Preprocessing",
        "tab_model": "🧠 Model & Evaluation",
        "tab_predict": "🔮 Prediction",
        # Tab 1
        "load_data_first": "⬅️ Please load data from the sidebar first.",
        "total_reviews": "Total Reviews",
        "positive": "Positive",
        "neutral": "Neutral",
        "negative": "Negative",
        "rating_dist": "Rating Distribution",
        "sentiment_dist": "Sentiment Distribution",
        "reviews_per_version": "Reviews per App Version",
        "data_table": "📋 Review Data Table",
        "export_csv": "📥 Export CSV",
        "export_pdf": "📄 Export PDF Report",
        # Tab 2
        "train_first": "⬅️ Please train the model first to see preprocessing results.",
        "before_after": "Before / After Preprocessing",
        "original_review": "Original Review",
        "after_preprocess": "After Preprocessing",
        "sentiment": "Sentiment",
        "wordcloud_title": "☁️ Word Cloud per Sentiment",
        "no_data": "No data available.",
        # Tab 3
        "train_first_model": "⬅️ Please train the model from the sidebar first.",
        "confusion_matrix": "Confusion Matrix",
        "classification_report": "Classification Report",
        "prediction_label": "Prediction",
        "actual_label": "Actual",
        "count_label": "Count",
        "ngram_label": "N-Gram",
        "train_size_label": "Train size",
        "test_size_label": "Test size",
        "total_features": "Total features",
        "ngram_comparison": "📊 N-Gram Performance Comparison",
        "click_compare": "Click **Compare N-Grams** in the sidebar to compare all configurations.",
        "score_label": "Score (%)",
        "metric_label": "Metric",
        "export_model_pdf": "📄 Export Model Report (PDF)",
        # Tab 4
        "predict_title": "🔮 Manual Sentiment Prediction",
        "predict_input": "Enter review text to predict",
        "predict_placeholder": "Example: This game is amazing and the graphics are so cool!",
        "predict_btn": "🔍 Predict",
        "predict_result": "Prediction Result",
        "prob_per_class": "Probability per Class",
        "detail_preprocess": "🔍 Preprocessing Detail",
        "original_text": "Original text",
        "after_preprocess_text": "After preprocessing",
        "enter_text_first": "Please enter text first.",
        "example_texts": "💡 Example Texts",
        # Training
        "preprocess_spinner": "⏳ Preprocessing text...",
        "train_spinner": "🧠 Training Naïve Bayes model...",
        "train_success": "✅ Model trained successfully!",
        "compare_spinner": "📊 Comparing all N-Gram configurations...",
        "compare_success": "✅ Comparison complete!",
    },

    "id": {
        "lang_name": "Bahasa Indonesia",
        # Sidebar
        "sidebar_title": "PUBG Mobile",
        "sidebar_subtitle": "Analisis Sentimen",
        "data_source": "Sumber Data",
        "data_source_sample": "Data Default (Sample)",
        "data_source_scrape": "Scrape Data Asli",
        "data_source_upload": "Upload CSV",
        "upload_csv": "Upload file CSV",
        "load_sample": "🔄 Muat Data Sample",
        "load_sample_spinner": "Membuat data sample...",
        "load_sample_success": "review dimuat",
        "rows_loaded": "baris dimuat",
        "scrape_btn": "🔍 Scrape & Muat Data",
        "scrape_spinner": "Scraping {count} ulasan dari App Store ({countries})...",
        "scrape_success": "ulasan berhasil diambil!",
        "scrape_fail": "❌ Gagal mengambil data. Pastikan koneksi internet stabil.",
        "select_countries": "Pilih Negara",
        "select_all": "Pilih Semua Negara",
        "review_count": "Jumlah Total Ulasan",
        "filter_version": "🔖 Filter Versi Aplikasi",
        "model_config": "⚙️ Konfigurasi Model",
        "ngram_type": "Tipe N-Gram",
        "use_stemming": "Gunakan Stemming",
        "test_size": "Ukuran Test Set (%)",
        "train_btn": "🚀 Latih Model",
        "compare_btn": "📊 Bandingkan N-Gram",
        "language_label": "🌐 Bahasa",
        "copyright": "© 2025 — Naïve Bayes N-Gram Sentiment Analysis",
        # Hero banner
        "hero_title": "🎮 Analisis Sentimen PUBG Mobile",
        "hero_desc": "Dashboard interaktif untuk menganalisis sentimen ulasan App Store menggunakan Naïve Bayes Classifier & N-Gram",
        # Tabs
        "tab_explore": "📊 Eksplorasi Data",
        "tab_preprocess": "🔧 Preprocessing",
        "tab_model": "🧠 Model & Evaluasi",
        "tab_predict": "🔮 Prediksi",
        # Tab 1
        "load_data_first": "⬅️ Muat data terlebih dahulu dari sidebar.",
        "total_reviews": "Total Review",
        "positive": "Positif",
        "neutral": "Netral",
        "negative": "Negatif",
        "rating_dist": "Distribusi Rating",
        "sentiment_dist": "Distribusi Sentimen",
        "reviews_per_version": "Jumlah Review per Versi Aplikasi",
        "data_table": "📋 Tabel Data Review",
        "export_csv": "📥 Ekspor CSV",
        "export_pdf": "📄 Ekspor Laporan PDF",
        # Tab 2
        "train_first": "⬅️ Latih model terlebih dahulu untuk melihat hasil preprocessing.",
        "before_after": "Sebelum / Sesudah Preprocessing",
        "original_review": "Review Asli",
        "after_preprocess": "Setelah Preprocessing",
        "sentiment": "Sentimen",
        "wordcloud_title": "☁️ Word Cloud per Sentimen",
        "no_data": "Tidak ada data.",
        # Tab 3
        "train_first_model": "⬅️ Latih model terlebih dahulu dari sidebar.",
        "confusion_matrix": "Confusion Matrix",
        "classification_report": "Classification Report",
        "prediction_label": "Prediksi",
        "actual_label": "Aktual",
        "count_label": "Jumlah",
        "ngram_label": "N-Gram",
        "train_size_label": "Train size",
        "test_size_label": "Test size",
        "total_features": "Total fitur (features)",
        "ngram_comparison": "📊 Perbandingan Performa N-Gram",
        "click_compare": "Klik **Bandingkan N-Gram** di sidebar untuk membandingkan semua konfigurasi.",
        "score_label": "Skor (%)",
        "metric_label": "Metrik",
        "export_model_pdf": "📄 Ekspor Laporan Model (PDF)",
        # Tab 4
        "predict_title": "🔮 Prediksi Sentimen Teks Manual",
        "predict_input": "Masukkan teks review untuk diprediksi",
        "predict_placeholder": "Contoh: Game ini sangat seru dan grafisnya bagus banget!",
        "predict_btn": "🔍 Prediksi",
        "predict_result": "Hasil Prediksi",
        "prob_per_class": "Probabilitas per Kelas",
        "detail_preprocess": "🔍 Detail Preprocessing",
        "original_text": "Teks asli",
        "after_preprocess_text": "Setelah preprocessing",
        "enter_text_first": "Masukkan teks terlebih dahulu.",
        "example_texts": "💡 Contoh Teks",
        # Training
        "preprocess_spinner": "⏳ Preprocessing teks...",
        "train_spinner": "🧠 Melatih model Naïve Bayes...",
        "train_success": "✅ Model berhasil dilatih!",
        "compare_spinner": "📊 Membandingkan semua konfigurasi N-Gram...",
        "compare_success": "✅ Perbandingan selesai!",
    },
}


def get_lang(lang_code="en"):
    """Get translation dictionary for given language code."""
    return LANGUAGES.get(lang_code, LANGUAGES["en"])
