"""
Multi-language UI translation dictionaries.
Only UI labels are translated — NLP preprocessing remains Indonesian-focused.
"""

LANGUAGES = {
    "en": {
        "lang_name": "English",
        # Navigation
        "nav_overview": "Overview",
        "nav_upload": "Upload Dataset",
        "nav_exploration": "Data Exploration",
        "nav_preprocessing": "Preprocessing",
        "nav_ngram": "N-Gram Extraction",
        "nav_classification": "Sentiment Classification",
        "nav_train": "Train Model",
        "nav_evaluation": "Model Evaluation",
        "nav_visualization": "Visualization",
        "nav_wordcloud": "Word Cloud",
        "nav_prediction": "Prediction",
        "nav_recommendations": "Developer Recommendations",
        "nav_about": "About Research",
        "nav_cat_data": "DATA",
        "nav_cat_analysis": "ANALYSIS",
        "nav_cat_results": "RESULTS & INSIGHTS",
        "nav_cat_info": "INFO",
        # Redirect helpers
        "go_to_train": "Go to Train Model",
        "go_to_upload": "Go to Upload Dataset",
        "train_page_desc": "Configure parameters and train the Naïve Bayes model for sentiment classification.",
        "train_done_hint": "💡 See detailed results in **📋 Model Evaluation** or try predictions in **🔮 Prediction**.",
        # Sidebar
        "sidebar_title": "PUBG Mobile",
        "sidebar_subtitle": "Sentiment Analysis",
        "data_source": "Data Source",
        "data_source_sample": "Default Data (Sample)",
        "data_source_scrape": "Scrape Real Data",
        "data_source_upload": "Upload CSV",
        "upload_csv": "Upload CSV file",
        "load_sample": "🔄 Load Sample Data",
        "load_sample_spinner": "Generating sample data...",
        "load_sample_success": "reviews loaded",
        "rows_loaded": "rows loaded",
        "scrape_btn": "🔍 Scrape & Load Data",
        "scrape_spinner": "Scraping {count} reviews from App Store ({countries})...",
        "scrape_success": "reviews successfully scraped!",
        "scrape_fail": "❌ Failed to fetch data. Please check your internet connection.",
        "select_countries": "Select Countries",
        "select_all": "Select All Countries",
        "review_count": "Total Reviews",
        "filter_version": "🔖 Filter App Version",
        "model_config": "⚙️ Model Configuration",
        "ngram_type": "N-Gram Type",
        "use_stemming": "Use Stemming",
        "test_size": "Test Set Size (%)",
        "train_btn": "🚀 Train Model",
        "compare_btn": "📊 Compare N-Grams",
        "language_label": "🌐 Language",
        "copyright": "© 2025 — OctaLectzz - Naïve Bayes N-Gram Sentiment Analysis",
        # Hero banner
        "hero_title": "🎮 PUBG Mobile Sentiment Analysis",
        "hero_desc": "Interactive dashboard for analyzing App Store review sentiments using Naïve Bayes Classifier & N-Gram",
        # Data status
        "data_loaded": "Data loaded",
        "data_not_loaded": "No data loaded",
        "model_trained": "Model trained",
        "model_not_trained": "⚠️ Model not trained yet. Go to **🧠 Sentiment Classification** to train.",
        # Overview
        "quickstart_title": "Quick Start",
        "quickstart_desc": "Follow these steps to start sentiment analysis:",
        "quickstart_info": "👈 Use the **📂 Upload Dataset** menu in sidebar to load data.",
        "step1_title": "Load Data",
        "step1_desc": "Go to Upload Dataset to load sample data, scrape from App Store, or upload a CSV file.",
        "step2_title": "Train Model",
        "step2_desc": "Configure N-Gram in sidebar, then train the Naïve Bayes model from Classification menu.",
        "step3_title": "Analyze Results",
        "step3_desc": "Explore model evaluation, visualizations, word clouds, and sentiment predictions.",
        "recent_reviews": "Recent Reviews",
        # Upload
        "upload_desc": "Choose a data source to start sentiment analysis.",
        "sample_title": "PUBG Mobile Sample Data",
        "sample_desc": "Use sample data containing 100 PUBG Mobile reviews in Indonesian for quick demo and testing.",
        "scrape_title": "Scrape Reviews from Apple App Store",
        "scrape_desc": "Fetch real-time review data from App Store across various countries using RSS Feed.",
        "csv_title": "Upload CSV File",
        "csv_desc": "Upload your own CSV file. Make sure it contains <code>review_text</code> and <code>rating</code> columns.",
        "data_preview": "Loaded Data Preview",
        "avg_rating": "Average Rating",
        "dominant_sentiment": "Dominant Sentiment",
        "no_data_yet": "📭 No data loaded yet. Choose a data source above.",
        # Tab 1 - Exploration
        "load_data_first": "⬅️ Please load data from the sidebar first.",
        "total_reviews": "Total Reviews",
        "positive": "Positive",
        "neutral": "Neutral",
        "negative": "Negative",
        "rating_dist": "Rating Distribution",
        "sentiment_dist": "Sentiment Distribution",
        "reviews_per_version": "Reviews per App Version",
        "data_table": "📋 Review Data Table",
        "export_csv": "📥 Export CSV",
        "export_pdf": "📄 Export PDF Report",
        "count_label": "Count",
        # Tab 2 - Preprocessing
        "train_first": "⬅️ Please train the model first to see preprocessing results.",
        "before_after": "Before / After Preprocessing",
        "original_review": "Original Review",
        "after_preprocess": "After Preprocessing",
        "sentiment": "Sentiment",
        "wordcloud_title": "☁️ Word Cloud per Sentiment",
        "no_data": "No data available.",
        "preprocess_page_desc": "Text cleaning pipeline to prepare data before classification.",
        "pipeline_title": "Preprocessing Pipeline",
        "step_casefolding": "Convert all text to lowercase.",
        "step_normalize": "Normalize repeated characters: 'baguuuus' → 'bagus'.",
        "step_cleaning": "Remove URLs, mentions, hashtags, emojis, numbers, and special characters.",
        "step_slang": "Convert slang/abbreviations to standard form using dictionary.",
        "step_negation": "Combine negation word with next word: 'tidak bagus' → 'tidak_bagus'.",
        "step_stopword": "Remove common non-meaningful words while keeping sentiment words.",
        "step_stemming": "Reduce words to root form using PySastrawi (optional).",
        "stemming_note": "Change in model configuration in sidebar.",
        "words_before": "Total Words (Before)",
        "words_after": "Total Words (After)",
        "vocab_before": "Vocabulary (Before)",
        "vocab_after": "Vocabulary (After)",
        # N-Gram
        "ngram_page_desc": "Analysis of N-Gram features extracted from review text.",
        "ngram_what": "What is N-Gram?",
        "unigram_desc": "Single word as feature.",
        "bigram_desc": "Pair of two consecutive words.",
        "trigram_desc": "Combination of three consecutive words.",
        "ngram_tfidf_note": "💡 N-Gram features are extracted using **TF-IDF Vectorizer** which measures the importance of each N-Gram in a document relative to the entire corpus.",
        "ngram_feature_info": "Feature Information",
        "ngram_range_label": "N-Gram Range",
        "best_alpha": "Best Alpha",
        "top_features": "Top N-Gram Features",
        "top_n_slider": "Number of top features",
        "ngram_distribution": "N-Gram Length Distribution",
        # Classification
        "classification_desc": "Train Naïve Bayes model and compare N-Gram configurations.",
        "current_config": "Current Configuration",
        "train_section": "Model Training",
        "train_model_title": "Train Naïve Bayes Model",
        "train_model_desc": "Train Complement Naïve Bayes model with GridSearchCV for hyperparameter tuning.",
        "compare_title": "Compare N-Grams",
        "compare_desc": "Compare performance of all N-Gram configurations to find the best one.",
        "training_results": "Training Results",
        "best_ngram": "Best N-Gram",
        # Tab 3 - Model
        "train_first_model": "⬅️ Please train the model from the sidebar first.",
        "confusion_matrix": "Confusion Matrix",
        "classification_report": "Classification Report",
        "prediction_label": "Prediction",
        "actual_label": "Actual",
        "ngram_label": "N-Gram",
        "train_size_label": "Train size",
        "test_size_label": "Test size",
        "total_features": "Total features",
        "ngram_comparison": "📊 N-Gram Performance Comparison",
        "click_compare": "Click **Compare N-Grams** in the sidebar to compare all configurations.",
        "score_label": "Score (%)",
        "metric_label": "Metric",
        "export_model_pdf": "📄 Export Model Report (PDF)",
        "per_class_perf": "Per-Class Performance",
        "model_info": "Model Information",
        # Tab 4 - Prediction
        "predict_title": "🔮 Manual Sentiment Prediction",
        "predict_input": "Enter review text to predict",
        "predict_placeholder": "Example: This game is amazing and the graphics are so cool!",
        "predict_btn": "🔍 Predict",
        "predict_result": "Prediction Result",
        "prob_per_class": "Probability per Class",
        "detail_preprocess": "🔍 Preprocessing Detail",
        "original_text": "Original text",
        "after_preprocess_text": "After preprocessing",
        "enter_text_first": "Please enter text first.",
        "example_texts": "💡 Example Texts",
        "predict_page_desc": "Enter review text to predict its sentiment in real-time.",
        "predict_history": "Prediction History",
        # Recommendations
        "rec_desc": "Automatic insights and recommendations based on sentiment analysis.",
        "rec_summary": "Sentiment Summary",
        "rec_complaints": "Top Complaints (from Negative Reviews)",
        "rec_highlights": "What Users Love",
        "rec_actions": "Actionable Recommendations for Developers",
        "rec_high_neg": "High negative sentiment rate (>30%). Prioritize bug fixes and performance.",
        "rec_mid_neg": "Moderate negative sentiment rate (15-30%). Focus on main negative feedback.",
        "rec_low_neg": "Overall positive sentiment. Maintain quality and keep innovating.",
        "rec_perf": "Optimize game performance for mid-range and low-end devices.",
        "rec_cheat": "Improve anti-cheat system and speed up cheater reporting process.",
        "rec_bug": "Conduct thorough QA testing before releasing updates.",
        "rec_server": "Upgrade server infrastructure, especially in Southeast Asia region.",
        "rec_monetize": "Review monetization model. Consider offering more free content.",
        "rec_sample_neg": "Sample Top Negative Reviews",
        # About
        "about_title": "PUBG Mobile Review Sentiment Analysis",
        "about_subtitle": "Using Naïve Bayes Classifier with N-Gram Feature Extraction",
        "about_methodology": "Research Methodology",
        "about_nb": "Naïve Bayes Algorithm",
        "about_ngram": "N-Gram Features",
        "about_tech": "Technology Stack",
        "about_credits": "Credits",
        "about_method_label": "Method: Naïve Bayes Classifier with N-Gram Feature Extraction",
        # Visualization
        "viz_desc": "Interactive visualizations for in-depth sentiment data exploration.",
        "viz_trend": "Sentiment Trend Over Time",
        "viz_heatmap": "Rating and Sentiment Correlation",
        "viz_country": "Sentiment Distribution by Country",
        "viz_topwords": "Top Words per Sentiment",
        "topwords_slider": "Number of top words",
        "viz_violin": "Rating Distribution per Sentiment",
        "country_label": "Country",
        # Word Cloud
        "wc_desc": "Visualization of the most frequently occurring words in each sentiment category.",
        "wc_settings": "Word Cloud Settings",
        "wc_max_words": "Maximum Words",
        "wc_background": "Background",
        "wc_transparent": "Transparent",
        "wc_white": "White",
        "wc_dark": "Dark",
        "wc_combined": "Combined Word Cloud (All Sentiments)",
        # Training
        "preprocess_spinner": "⏳ Preprocessing text...",
        "train_spinner": "🧠 Training Naïve Bayes model...",
        "train_success": "✅ Model trained successfully!",
        "compare_spinner": "📊 Comparing all N-Gram configurations...",
        "compare_success": "✅ Comparison complete!",
    },

    "id": {
        "lang_name": "Bahasa Indonesia",
        # Navigation
        "nav_overview": "Overview",
        "nav_upload": "Upload Dataset",
        "nav_exploration": "Eksplorasi Data",
        "nav_preprocessing": "Preprocessing",
        "nav_ngram": "Ekstraksi N-Gram",
        "nav_classification": "Klasifikasi Sentimen",
        "nav_train": "Latih Model",
        "nav_evaluation": "Evaluasi Model",
        "nav_visualization": "Visualisasi",
        "nav_wordcloud": "Word Cloud",
        "nav_prediction": "Prediksi",
        "nav_recommendations": "Rekomendasi Developer",
        "nav_about": "Tentang Penelitian",
        "nav_cat_data": "DATA",
        "nav_cat_analysis": "ANALISIS",
        "nav_cat_results": "HASIL & INSIGHT",
        "nav_cat_info": "INFO",
        # Redirect helpers
        "go_to_train": "Pergi ke Latih Model",
        "go_to_upload": "Pergi ke Upload Dataset",
        "train_page_desc": "Konfigurasi parameter dan latih model Naïve Bayes untuk klasifikasi sentimen.",
        "train_done_hint": "💡 Lihat hasil detail di menu **📋 Evaluasi Model** atau coba prediksi di **🔮 Prediksi**.",
        # Sidebar
        "sidebar_title": "PUBG Mobile",
        "sidebar_subtitle": "Analisis Sentimen",
        "data_source": "Sumber Data",
        "data_source_sample": "Data Default (Sample)",
        "data_source_scrape": "Scrape Data Asli",
        "data_source_upload": "Upload CSV",
        "upload_csv": "Upload file CSV",
        "load_sample": "🔄 Muat Data Sample",
        "load_sample_spinner": "Membuat data sample...",
        "load_sample_success": "review dimuat",
        "rows_loaded": "baris dimuat",
        "scrape_btn": "🔍 Scrape & Muat Data",
        "scrape_spinner": "Scraping {count} ulasan dari App Store ({countries})...",
        "scrape_success": "ulasan berhasil diambil!",
        "scrape_fail": "❌ Gagal mengambil data. Pastikan koneksi internet stabil.",
        "select_countries": "Pilih Negara",
        "select_all": "Pilih Semua Negara",
        "review_count": "Jumlah Total Ulasan",
        "filter_version": "🔖 Filter Versi Aplikasi",
        "model_config": "⚙️ Konfigurasi Model",
        "ngram_type": "Tipe N-Gram",
        "use_stemming": "Gunakan Stemming",
        "test_size": "Ukuran Test Set (%)",
        "train_btn": "🚀 Latih Model",
        "compare_btn": "📊 Bandingkan N-Gram",
        "language_label": "🌐 Bahasa",
        "copyright": "© 2025 — OctaLectzz - Naïve Bayes N-Gram Sentiment Analysis",
        # Hero banner
        "hero_title": "🎮 Analisis Sentimen PUBG Mobile",
        "hero_desc": "Dashboard interaktif untuk menganalisis sentimen ulasan App Store menggunakan Naïve Bayes Classifier & N-Gram",
        # Data status
        "data_loaded": "Data dimuat",
        "data_not_loaded": "Belum ada data",
        "model_trained": "Model telah dilatih",
        "model_not_trained": "⚠️ Model belum dilatih. Buka menu **🧠 Klasifikasi Sentimen** untuk melatih model.",
        # Overview
        "quickstart_title": "Mulai Cepat",
        "quickstart_desc": "Ikuti langkah berikut untuk memulai analisis sentimen:",
        "quickstart_info": "👈 Gunakan menu **📂 Upload Dataset** di sidebar untuk memuat data.",
        "step1_title": "Muat Data",
        "step1_desc": "Buka menu Upload Dataset untuk memuat data sample, scrape dari App Store, atau upload CSV.",
        "step2_title": "Latih Model",
        "step2_desc": "Konfigurasi N-Gram di sidebar, lalu latih model Naïve Bayes dari menu Klasifikasi.",
        "step3_title": "Analisis Hasil",
        "step3_desc": "Jelajahi evaluasi model, visualisasi, word cloud, dan prediksi sentimen.",
        "recent_reviews": "Review Terbaru",
        # Upload
        "upload_desc": "Pilih sumber data untuk memulai analisis sentimen.",
        "sample_title": "Data Sample PUBG Mobile",
        "sample_desc": "Gunakan data sample berisi 100 review PUBG Mobile dalam Bahasa Indonesia untuk demo dan pengujian cepat.",
        "scrape_title": "Scrape Review dari Apple App Store",
        "scrape_desc": "Ambil data review secara real-time dari App Store berbagai negara menggunakan RSS Feed.",
        "csv_title": "Upload File CSV",
        "csv_desc": "Upload file CSV Anda sendiri. Pastikan terdapat kolom <code>review_text</code> dan <code>rating</code>.",
        "data_preview": "Preview Data yang Dimuat",
        "avg_rating": "Rata-rata Rating",
        "dominant_sentiment": "Sentimen Dominan",
        "no_data_yet": "📭 Belum ada data dimuat. Pilih salah satu sumber data di atas.",
        # Tab 1 - Exploration
        "load_data_first": "⬅️ Muat data terlebih dahulu dari sidebar.",
        "total_reviews": "Total Review",
        "positive": "Positif",
        "neutral": "Netral",
        "negative": "Negatif",
        "rating_dist": "Distribusi Rating",
        "sentiment_dist": "Distribusi Sentimen",
        "reviews_per_version": "Jumlah Review per Versi Aplikasi",
        "data_table": "📋 Tabel Data Review",
        "export_csv": "📥 Ekspor CSV",
        "export_pdf": "📄 Ekspor Laporan PDF",
        "count_label": "Jumlah",
        # Tab 2 - Preprocessing
        "train_first": "⬅️ Latih model terlebih dahulu untuk melihat hasil preprocessing.",
        "before_after": "Sebelum / Sesudah Preprocessing",
        "original_review": "Review Asli",
        "after_preprocess": "Setelah Preprocessing",
        "sentiment": "Sentimen",
        "wordcloud_title": "☁️ Word Cloud per Sentimen",
        "no_data": "Tidak ada data.",
        "preprocess_page_desc": "Pipeline pembersihan teks untuk mempersiapkan data sebelum klasifikasi.",
        "pipeline_title": "Pipeline Preprocessing",
        "step_casefolding": "Mengubah semua teks menjadi huruf kecil (lowercase).",
        "step_normalize": "Menormalkan karakter berulang: 'baguuuus' → 'bagus'.",
        "step_cleaning": "Menghapus URL, mention, hashtag, emoji, angka, dan karakter spesial.",
        "step_slang": "Mengubah kata slang/singkatan ke bentuk baku menggunakan kamus.",
        "step_negation": "Menggabungkan kata negasi dengan kata berikutnya: 'tidak bagus' → 'tidak_bagus'.",
        "step_stopword": "Menghapus kata-kata umum yang tidak bermakna, dengan tetap menyimpan kata sentimen.",
        "step_stemming": "Mengubah kata ke bentuk dasar menggunakan PySastrawi (opsional).",
        "stemming_note": "Ubah di konfigurasi model pada sidebar.",
        "words_before": "Total Kata (Sebelum)",
        "words_after": "Total Kata (Sesudah)",
        "vocab_before": "Vocabulary (Sebelum)",
        "vocab_after": "Vocabulary (Sesudah)",
        # N-Gram
        "ngram_page_desc": "Analisis fitur N-Gram yang diekstrak dari teks review.",
        "ngram_what": "Apa itu N-Gram?",
        "unigram_desc": "Satu kata tunggal sebagai fitur.",
        "bigram_desc": "Pasangan dua kata berurutan.",
        "trigram_desc": "Kombinasi tiga kata berurutan.",
        "ngram_tfidf_note": "💡 Fitur N-Gram diekstrak menggunakan **TF-IDF Vectorizer** yang mengukur kepentingan setiap N-Gram dalam dokumen relatif terhadap seluruh korpus.",
        "ngram_feature_info": "Informasi Fitur",
        "ngram_range_label": "N-Gram Range",
        "best_alpha": "Best Alpha",
        "top_features": "Top N-Gram Features",
        "top_n_slider": "Jumlah fitur teratas",
        "ngram_distribution": "Distribusi Panjang N-Gram",
        # Classification
        "classification_desc": "Latih model Naïve Bayes dan bandingkan konfigurasi N-Gram.",
        "current_config": "Konfigurasi Saat Ini",
        "train_section": "Pelatihan Model",
        "train_model_title": "Latih Model Naïve Bayes",
        "train_model_desc": "Melatih model Complement Naïve Bayes dengan GridSearchCV untuk hyperparameter tuning.",
        "compare_title": "Bandingkan N-Gram",
        "compare_desc": "Membandingkan performa semua konfigurasi N-Gram untuk menemukan yang terbaik.",
        "training_results": "Hasil Pelatihan",
        "best_ngram": "N-Gram Terbaik",
        # Tab 3 - Model
        "train_first_model": "⬅️ Latih model terlebih dahulu dari menu Klasifikasi.",
        "confusion_matrix": "Confusion Matrix",
        "classification_report": "Classification Report",
        "prediction_label": "Prediksi",
        "actual_label": "Aktual",
        "ngram_label": "N-Gram",
        "train_size_label": "Train size",
        "test_size_label": "Test size",
        "total_features": "Total fitur (features)",
        "ngram_comparison": "📊 Perbandingan Performa N-Gram",
        "click_compare": "Klik **Bandingkan N-Gram** di sidebar untuk membandingkan semua konfigurasi.",
        "score_label": "Skor (%)",
        "metric_label": "Metrik",
        "export_model_pdf": "📄 Ekspor Laporan Model (PDF)",
        "per_class_perf": "Performa per Kelas",
        "model_info": "Informasi Model",
        # Tab 4 - Prediction
        "predict_title": "🔮 Prediksi Sentimen Teks Manual",
        "predict_input": "Masukkan teks review untuk diprediksi",
        "predict_placeholder": "Contoh: Game ini sangat seru dan grafisnya bagus banget!",
        "predict_btn": "🔍 Prediksi",
        "predict_result": "Hasil Prediksi",
        "prob_per_class": "Probabilitas per Kelas",
        "detail_preprocess": "🔍 Detail Preprocessing",
        "original_text": "Teks asli",
        "after_preprocess_text": "Setelah preprocessing",
        "enter_text_first": "Masukkan teks terlebih dahulu.",
        "example_texts": "💡 Contoh Teks",
        "predict_page_desc": "Masukkan teks review untuk memprediksi sentimennya secara real-time.",
        "predict_history": "Riwayat Prediksi",
        # Recommendations
        "rec_desc": "Insight otomatis dan rekomendasi berdasarkan analisis sentimen review.",
        "rec_summary": "Ringkasan Sentimen",
        "rec_complaints": "Keluhan Utama (dari Review Negatif)",
        "rec_highlights": "Hal yang Disukai Pengguna",
        "rec_actions": "Rekomendasi Aksi untuk Developer",
        "rec_high_neg": "Tingkat sentimen negatif tinggi (>30%). Prioritaskan perbaikan bug dan performa.",
        "rec_mid_neg": "Tingkat sentimen negatif moderat (15-30%). Fokus pada feedback negatif utama.",
        "rec_low_neg": "Sentimen secara keseluruhan positif. Pertahankan kualitas dan terus berinovasi.",
        "rec_perf": "Optimasi performa game untuk perangkat mid-range dan low-end.",
        "rec_cheat": "Tingkatkan sistem anti-cheat dan percepat proses report cheater.",
        "rec_bug": "Lakukan QA testing menyeluruh sebelum release update.",
        "rec_server": "Tingkatkan infrastruktur server, terutama di region Asia Tenggara.",
        "rec_monetize": "Review ulang model monetisasi. Pertimbangkan menawarkan lebih banyak konten gratis.",
        "rec_sample_neg": "Contoh Review Negatif Teratas",
        # About
        "about_title": "Analisis Sentimen Review PUBG Mobile",
        "about_subtitle": "Menggunakan Metode Naïve Bayes Classifier dengan Ekstraksi Fitur N-Gram",
        "about_methodology": "Metodologi Penelitian",
        "about_nb": "Algoritma Naïve Bayes",
        "about_ngram": "Fitur N-Gram",
        "about_tech": "Teknologi yang Digunakan",
        "about_credits": "Kredit",
        "about_method_label": "Metode: Naïve Bayes Classifier dengan N-Gram Feature Extraction",
        # Visualization
        "viz_desc": "Visualisasi interaktif untuk eksplorasi data sentimen secara mendalam.",
        "viz_trend": "Tren Sentimen Berdasarkan Waktu",
        "viz_heatmap": "Korelasi Rating dan Sentimen",
        "viz_country": "Distribusi Sentimen per Negara",
        "viz_topwords": "Kata Teratas per Sentimen",
        "topwords_slider": "Jumlah kata teratas",
        "viz_violin": "Distribusi Rating per Sentimen",
        "country_label": "Negara",
        # Word Cloud
        "wc_desc": "Visualisasi kata-kata yang paling sering muncul dalam setiap kategori sentimen.",
        "wc_settings": "Pengaturan Word Cloud",
        "wc_max_words": "Maksimum Kata",
        "wc_background": "Background",
        "wc_transparent": "Transparan",
        "wc_white": "Putih",
        "wc_dark": "Gelap",
        "wc_combined": "Word Cloud Gabungan (Semua Sentimen)",
        # Training
        "preprocess_spinner": "⏳ Preprocessing teks...",
        "train_spinner": "🧠 Melatih model Naïve Bayes...",
        "train_success": "✅ Model berhasil dilatih!",
        "compare_spinner": "📊 Membandingkan semua konfigurasi N-Gram...",
        "compare_success": "✅ Perbandingan selesai!",
    },
}


def get_lang(lang_code="id"):
    """Get translation dictionary for given language code."""
    return LANGUAGES.get(lang_code, LANGUAGES["id"])
